# Generated by Django 3.2.23 on 2024-01-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('publication_date', models.DateTimeField(db_column='PublicationDate')),
                ('sentiment_score', models.FloatField(db_column='SentimentScore')),
                ('sentiment_label', models.CharField(db_column='SentimentLabel', max_length=15)),
                ('news_source', models.CharField(db_column='NewsSource', max_length=255, unique=True)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=255, null=True)),
                ('category_id', models.ForeignKey(db_column='CategoryId', on_delete=django.db.models.deletion.DO_NOTHING, to='news_catalog.category')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsUkrainian',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('headline', models.CharField(db_column='Headline', max_length=300)),
                ('content', models.TextField(db_column='Content')),
                ('news_id', models.OneToOneField(db_column='NewsId', on_delete=django.db.models.deletion.DO_NOTHING, to='news_catalog.news')),
            ],
            options={
                'db_table': 'NewsUkrainian',
            },
        ),
        migrations.CreateModel(
            name='NewsEnglish',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('headline', models.CharField(db_column='Headline', max_length=300)),
                ('content', models.TextField(db_column='Content')),
                ('news_id', models.OneToOneField(db_column='NewsId', on_delete=django.db.models.deletion.DO_NOTHING, to='news_catalog.news')),
            ],
            options={
                'db_table': 'NewsEnglish',
            },
        ),
    ]
